### ISSUE TITLE
Insert Copyright blurb using a pre-commit hook

### ISSUE THREAD

**Issue by tschm** [cvxpy/cvxpy#2229]
Rather than asking to add a copyright notice you could achieve the same using a pre-commit hook.

**Comment by tschm** [comment]
I am using

```
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
        - id: insert-license
          files: ^(cvxpy)
          args:
            ['--license-filepath', 'copyright.txt']
```
