### ISSUE TITLE
Include ruff format in `pre-commit`

### ISSUE THREAD

**Issue by andresliszt** [cvxpy/cvxpy#2598]
I noticed that ruff formatting is not being done on commits. The `pre-commit.yaml` file is

```yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.1.11'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
```

According to [ruff official docs](https://docs.astral.sh/ruff/formatter/#sorting-imports) they do not support (yet: _A unified command for both linting and formatting is planned_) formatting and linting in a single command. Running ruff format in the source code shows several files that must be formatted.

It makes it a bit difficult to create a PR if the code formatting is out of sync with the master
